all:
	g++ -c matrix.cpp -o matrix.o
# 	g++ -c test.cpp -o test.o
# 	g++ matrix.o test.cpp -o test
# 	g++ matrix.o Multivariate_Newton.cpp -o Multi_Newton
	g++ matrix.o Least_Squares.cpp -o Least_Squares
	del *.o