all:
	g++ -c matrix.cpp -o matrix.o
# 	g++ -c test.cpp -o test.o
# 	g++ matrix.o test.cpp -o test
# 	g++ matrix.o Multivariate_Newton.cpp -o Multi_Newton
	g++ matrix.o Newton_divided_differences.cpp -o Newton_divided_differences
	g++ matrix.o Least_Squares.cpp -o Least_Squares
	g++ matrix.o QR_Factorization.cpp -o QR_Factorization
	g++ matrix.o Gauss_Newton.cpp -o Gauss_Newton
	del *.o